export const texts = {
  common: {
    appName: "StoryCraft",
    storyLibrary: "Kho truyện",
    autoSaved: "Đã tự động lưu",
    saveAsOption: "Lưu thành lựa chọn",
    previousPage: "Trang trước",
    close: "Đóng",
    confirm: "Xác nhận",
    cancel: "Hủy",
    unknownError: "Unknown error",
  },
  app: {
    errorBoundaryTitle: "Đã xảy ra lỗi hệ thống",
    errorBoundaryMessage:
      "Xin lỗi, đã có lỗi không mong muốn xảy ra. Vui lòng tải lại trang để tiếp tục.",
    errorBoundaryReload: "Tải lại trang",
  },
  home: {
    title: "Bắt đầu hành trình sáng tác",
    description: "Chọn một phương thức để bắt đầu câu chuyện của bạn.",
    libraryTitle: "Kho truyện",
    libraryDescription:
      "Mở lại truyện đã lưu trong máy, đọc nhanh, viết tiếp hoặc nhập JSON vào kho.",
    newWorldTitle: "Sáng tạo thế giới mới",
    newWorldDescription:
      "Bắt đầu từ con số không. Lên ý tưởng, tạo nhân vật và thiết lập quy tắc.",
    fanfictionTitle: "Đồng nhân (Fanfiction)",
    fanfictionDescription:
      "Tải lên file văn bản (.txt) chứa bối cảnh/cốt truyện gốc để AI viết tiếp.",
    importTitle: "Nhập file truyện đang viết",
    importDescription:
      "Tải lên file (.json) đã xuất trước đó để tiếp tục công việc.",
    invalidFileTitle: "Lỗi",
    invalidFileMessage: "File không hợp lệ!",
  },
  layout: {
    libraryLink: "Kho truyện",
    apiKeyLink: "API Key",
  },
  geminiKeyManager: {
    buttonTitle: "Quản lý Gemini API key",
    modalTitle: "Gemini API key cá nhân",
    modalDescription:
      "Key được lưu cục bộ trong trình duyệt này, tách riêng khỏi dữ liệu truyện và không đi theo file backup `.json`. Bạn cũng có thể đổi model AI mặc định ngay tại đây.",
    textModelTitle: "Model AI",
    textModelDescription:
      "Áp dụng cho viết tiếp, viết lại, đặt tên chương, quét lỗi và các tác vụ văn bản khác. Bạn có thể bấm preset nhanh hoặc tự nhập thẳng tên model.",
    textModelQuickLabel: "Chọn nhanh",
    textModelCustomLabel: "Tự nhập model",
    textModelCustomPlaceholder: "VD: gemini-2.5-pro, gemini-1.5-flash...",
    textModelApplyButton: "Dùng model này",
    textModelResetButton: "Về tự động",
    textModelAutoLabel: "Tự động theo app",
    textModelCurrentPrefix: "Model hiện tại:",
    textModelQuickOptions: {
      gemini31: {
        label: "Gemini 3.1",
        description: "Nhanh và ổn định cho đa số tác vụ viết truyện.",
      },
      gemini25: {
        label: "Gemini 2.5",
        description:
          "Tương thích tốt hơn với một số key hoặc quota khó tính.",
      },
    },
    labelPlaceholder: "Tên gợi nhớ: Key 1, Acc phụ...",
    valuePlaceholder: "Dán Gemini API key vào đây",
    saveButton: "Lưu key",
    enabledSummary: (enabledCount: number, totalCount: number) =>
      `${enabledCount}/${totalCount} key đang bật`,
    activeSummary: (label: string) => `Đang dùng: ${label}`,
    emptyState: "Chưa có Gemini API key nào trong trình duyệt này.",
    activeBadge: "Đang dùng",
    disabledBadge: "Đã tắt",
    cooldownBadge: (cooldownLabel: string) => `Nghỉ ${cooldownLabel}`,
    hideButton: "Ẩn",
    showButton: "Hiện",
    copyButton: "Copy",
    copiedButton: "Đã chép",
    copyTitle: "Sao chép key",
    lastErrorPrefix: "Lỗi gần nhất:",
    useThisKeyButton: "Dùng key này",
    retryNowButton: "Dùng lại ngay",
    disableButton: "Tạm tắt",
    enableButton: "Bật lại",
    deleteButton: "Xóa key",
    closeButton: "Đóng",
    addMissingTitle: "Thiếu API key",
    addMissingMessage: "Hãy dán Gemini API key trước khi lưu.",
    saveErrorTitle: "Không thể lưu key",
    saveErrorMessage: "Có lỗi xảy ra khi lưu Gemini API key.",
    switchErrorTitle: "Không thể đổi key",
    switchErrorMessage: "Không thể đặt key này làm key đang dùng.",
    toggleErrorTitle: "Không thể cập nhật key",
    toggleErrorMessage: "Có lỗi xảy ra khi cập nhật trạng thái key.",
    deleteConfirmTitle: "Xóa Gemini API key",
    deleteConfirmMessage: (label: string) =>
      `Bạn có chắc muốn xóa ${label} khỏi trình duyệt này không?`,
    deleteConfirmButton: "Xóa key",
  },
  savedOptions: {
    saveButton: "Lưu thành lựa chọn",
  },
  storyIdeaStep: {
    genres: [
      "1v1",
      "Biến thân",
      "Cao võ",
      "Chat group",
      "Chủ thần không gian",
      "Dị năng",
      "Dân gian",
      "Đô thị",
      "Hài hước",
      "Hậu cung",
      "Hệ thống",
      "Hồng hoang",
      "Huyền huyễn",
      "Làm ruộng",
      "Lãnh chúa",
      "Linh dị",
      "Nhẹ nhàng",
      "Nón hồng nô (vợ/người yêu nam chính chủ động đẩy nam chính vào lòng cô gái khác)",
      "Nón xanh (người yêu/vợ nam chính bị người khác chơi)",
      "Nữ tôn",
      "Phàm nhân",
      "Phản phái",
      "Phía sau màn",
      "Phế vật nghịch tập",
      "Sáng thế",
      "Sắc hiệp",
      "Tào tặc",
      "Tận thế",
      "Tây phương",
      "Thần hào",
      "Thần linh",
      "Thần thoại",
      "Thiên tài",
      "Tiến hóa",
      "Tiên hiệp",
      "Tiếng lòng",
      "Toàn dân",
      "Trực tiếp",
      "Trùng sinh",
      "Vạn giới",
      "Võ hiệp",
      "Võng du",
      "Vô hạn",
      "Xuyên không",
    ],
    title: "Trang 1: Ý tưởng truyện",
    description:
      "Thiết lập các thông số chi tiết để AI tạo ra các ý tưởng cốt truyện độc đáo.",
    genresLabel: "Thể loại",
    promptLabel: "Từ khóa / Ý tưởng chính",
    promptPlaceholder: "VD: Nhân vật chính trọng sinh...",
    worldSettingLabel: "Thiết lập thế giới",
    worldSettingPlaceholder: "VD: Tu chân giới, mạt thế, tinh tế...",
    resourcesLabel: "Tài nguyên",
    resourcesPlaceholder:
      "VD: Linh thạch, điểm tín ngưỡng, thọ mệnh...",
    racesLabel: "Chủng tộc",
    racesPlaceholder: "VD: Nhân loại, Yêu tộc, Ma tộc, Thần linh...",
    learningFilesLabel: "Học tập từ tài liệu (Tải lên nhiều file .txt, .md)",
    learningFilesUploadTitle: "Nhấn để tải lên tài liệu",
    learningFilesUploadHint: "Hỗ trợ file lớn lên đến 100MB+ (.txt, .md)",
    generateError: "Có lỗi xảy ra khi tạo ý tưởng.",
    generateButton: "Tạo ý tưởng",
    nextButton: "Trang kế (Hệ thống & Logic)",
    uploadTooLarge: (fileName: string) =>
      `File "${fileName}" quá lớn (>500KB). Vui lòng chọn file nhỏ hơn để đảm bảo hiệu năng.`,
  },
  pageWorld: {
    title: "Trang 2: Hệ thống & Logic thế giới",
    description:
      "Thiết lập chi tiết về cách thế giới vận hành và hệ thống sức mạnh của các nhân vật.",
    powerSystemLabel: "Hệ thống sức mạnh",
    powerSystemPlaceholder:
      "VD: Luyện khí - Trúc cơ - Kim đan... Hoặc hệ thống dị năng cấp bậc S, A, B... Hãy mô tả chi tiết các cấp bậc và sự chênh lệch sức mạnh giữa chúng.",
    worldLogicLabel: "Logic vận hành thế giới",
    worldLogicPlaceholder:
      "VD: Cá lớn nuốt cá bé, Thiên đạo vô tình, quy tắc bảo toàn năng lượng... Các quy luật vật lý, xã hội hoặc tâm linh chi phối thế giới này.",
    nextButton: "Trang kế (Nhân vật)",
  },
  characterStep: {
    title: "Trang 3: Phát triển nhân vật",
    description:
      "Thiết lập các thông số chi tiết để AI xây dựng hồ sơ nhân vật có chiều sâu.",
    mainCharacterLabel: "Tên nhân vật chính",
    mainCharacterPlaceholder: "VD: Tiêu Viêm, Hàn Lập, Đường Tam...",
    promptLabel: "Mô tả ngắn / Ý tưởng chung",
    promptPlaceholder:
      "VD: Một nữ sát thủ bị mất trí nhớ, luôn mang theo một chiếc đồng hồ quả quýt hỏng...",
    identityLabel: "Danh tính",
    identityPlaceholder: "VD: Thánh nữ ma giáo, Phế vật thiếu gia...",
    personalityLabel: "Tính cách",
    personalityPlaceholder: "VD: Lãnh khốc, sát phạt quả đoán, cẩn thận...",
    appearanceLabel: "Ngoại hình",
    appearancePlaceholder:
      "VD: Cao 1m8, tóc đen dài, mắt xanh, thường mặc áo bào trắng...",
    talentLabel: "Thiên phú",
    talentPlaceholder: "VD: Thần cấp kiếm cốt, Ngũ hành linh căn...",
    backgroundLabel: "Gia cảnh",
    backgroundPlaceholder: "VD: Cô nhi, Gia tộc sa sút, Hoàng tử thất sủng...",
    cheatLabel: "Kim thủ chỉ (Cheat)",
    cheatPlaceholder:
      "VD: Hệ thống đánh dấu, Lão gia gia trong nhẫn, Bảng panel thuộc tính...",
    supportingCharactersTitle: "Nhân vật phụ",
    supportingCharactersDescription:
      "Thêm các nhân vật quan trọng khác trong truyện.",
    addSupportingCharacter: "Thêm nhân vật phụ",
    noSupportingCharacters: "Chưa có nhân vật phụ nào được thêm.",
    supportingCharacterName: "Tên nhân vật",
    supportingCharacterNamePlaceholder: "Tên nhân vật phụ...",
    supportingCharacterIdentity: "Danh tính",
    supportingCharacterIdentityPlaceholder:
      "VD: Sư phụ, đối thủ, thanh mai trúc mã...",
    supportingCharacterPersonality: "Tính cách",
    supportingCharacterPersonalityPlaceholder:
      "VD: Hiền lành, mưu mô, trung thành...",
    supportingCharacterAppearance: "Ngoại hình",
    supportingCharacterAppearancePlaceholder:
      "VD: Xinh đẹp, lạnh lùng, mang theo kiếm...",
    supportingCharacterTalent: "Thiên phú",
    supportingCharacterTalentPlaceholder:
      "VD: Kiếm đạo thiên tài, luyện đan sư...",
    supportingCharacterBackground: "Gia cảnh",
    supportingCharacterBackgroundPlaceholder:
      "VD: Xuất thân hoàng tộc, tán tu...",
    generateError: "Có lỗi xảy ra khi phát triển nhân vật.",
    generateButton: "Phân tích & Xây dựng",
    nextButton: "Trang kế (Quy tắc)",
  },
  storyRules: {
    title: "Trang 4: Thiết lập quy tắc",
    description:
      "Thiết lập các điều cấm, khuyến khích và mức độ NSFW. AI sẽ tuân thủ nghiêm ngặt các quy tắc này khi viết truyện.",
    plannedChaptersLabel: "Số chương dự định",
    plannedChaptersHint:
      "AI sẽ dựa vào con số này để phân bổ cốt truyện và tiết tấu hợp lý.",
    forbiddenLabel: "Điều cấm",
    forbiddenPlaceholder:
      "VD: Không giết nhân vật phụ vô cớ, không dùng từ ngữ hiện đại...",
    encouragedLabel: "Điều khuyến khích",
    encouragedPlaceholder:
      "VD: Miêu tả chi tiết cảnh chiến đấu, sử dụng nhiều ẩn dụ...",
    commandsLabel: "Mệnh lệnh bắt buộc",
    commandsPlaceholder:
      "VD: Luôn giữ góc nhìn thứ nhất, nhân vật chính luôn phải tỏ ra lạnh lùng...",
    nsfwLabel: "Mức độ NSFW (18+)",
    startWriting: "Bắt đầu viết truyện",
    nsfwLevels: [
      {
        id: "Không",
        label: "Không",
        desc: "Không có nội dung 18+",
      },
      {
        id: "Nhẹ nhàng",
        label: "Nhẹ nhàng",
        desc: "Có các cảnh nhẹ nhàng như hôn môi nhưng tập trung chủ yếu vào cảm xúc của các nhân vật.",
      },
      {
        id: "Nâng cao",
        label: "Nâng cao",
        desc: "Ít chú ý vào nội tâm nhân vật mà tập trung chủ yếu vào các cảnh chịch.",
      },
      {
        id: "Hardcore",
        label: "Hardcore",
        desc: "Phá bỏ mọi giới hạn đạo đức thông thường, miêu tả trần trụi cảnh giao phối giữa các nhân vật, mở khóa nhiều thuộc tính biến thái trên các nhân vật.",
      },
    ],
  },
  storyIllustration: {
    parseErrorLog: "Failed to parse saved state for Page 4",
    quotaError:
      "Bạn đã hết lượt sử dụng AI hôm nay. Vui lòng thử lại vào ngày mai.",
    safetyError:
      "Mô tả của bạn bị bộ lọc an toàn từ chối hoặc vi phạm chính sách nội dung. Vui lòng thử mô tả khác lành mạnh, đơn giản hơn.",
    genericErrorPrefix: "Lỗi",
    genericErrorSuffix: "Vui lòng thử lại sau.",
    title: "Trang 6: Minh họa truyện",
    description:
      "Tạo hình ảnh minh họa chất lượng cao cho câu chuyện của bạn bằng AI.",
    promptLabel: "Mô tả hình ảnh",
    promptPlaceholder:
      "VD: Một khu rừng phát sáng kỳ ảo vào ban đêm, với những cây nấm khổng lồ...",
    generateButton: "Tạo ảnh minh họa",
    loadingText: "Đang vẽ tranh... (có thể mất vài chục giây)",
    downloadButton: "Tải xuống",
    generatedAlt: "Generated illustration",
    backToEditor: "Về trang viết truyện",
  },
  storyLibrary: {
    createError: "Khong the tao truyen moi. Vui long thu lai.",
    openError: "Khong mo duoc truyen nay.",
    deleteConfirm: "Ban co chac muon xoa truyen nay khoi kho truyen?",
    deleteError: "Khong xoa duoc truyen.",
    importError: "File JSON khong hop le hoac da bi hong.",
    eyebrow: "Kho truyện",
    title: "Thư viện truyện local của bạn",
    description:
      "Mỗi truyện được lưu sẵn trong máy. Lần sau mở app, bạn chỉ cần vào kho và chọn truyện để đọc hoặc viết tiếp.",
    importButton: "Nhập JSON",
    addStoryButton: "Thêm truyện mới",
    loadingText: "Đang tải kho truyện...",
    emptyTitle: "Kho truyện còn trống",
    emptyDescription:
      "Bạn có thể tạo truyện mới hoặc nhập file JSON đã xuất trước đó. Sau khi viết, mỗi lần lưu sẽ tự động cập nhật vào đây.",
    volumeUnit: "quyển",
    chapterUnit: "chương",
    characterUnit: "ký tự",
    updatedAtPrefix: "Cập nhật lúc",
    emptyExcerpt: "Chưa có nội dung tóm tắt. Mở truyện để bắt đầu viết.",
    readButton: "Đọc",
    openAndWriteButton: "Mở và viết tiếp",
    deleteButton: "Xóa",
  },
  storyReader: {
    loadingText: "Đang mở truyện...",
    notFoundTitle: "Không tìm thấy truyện",
    notFoundDescription:
      "Truyện này có thể đã bị xóa hoặc chưa được lưu đúng cách.",
    backToLibrary: "Quay lại kho truyện",
    libraryLink: "Về kho truyện",
    openInEditorButton: "Mở trong trình soạn thảo",
    chapterListTitle: "Danh sách chương",
    emptyChapterContent: "Chương này chưa có nội dung.",
    noChapters: "Truyện này chưa có chương nào để hiển thị.",
    volumeUnit: "quyển",
    chapterUnit: "chương",
    updatedPrefix: "cập nhật",
  },
  sharedStory: {
    notFoundError: "Không tìm thấy truyện hoặc link đã hết hạn.",
    loadingText: "Đang tải truyện...",
    errorTitle: "Ối! Có lỗi xảy ra",
    fallbackError: "Không tìm thấy nội dung yêu cầu.",
    backHome: "Về trang chủ",
    homeLink: "Trang chủ",
    copyDone: "Đã chép link",
    shareButton: "Chia sẻ",
    aiStudioAuthor: "Tác giả AI Studio",
    footerText: "Được tạo bởi AI Studio - Trình viết truyện thông minh",
    createYourOwn: "Tự tạo truyện của riêng bạn",
  },
} as const;
